[package]
name = "rust-essentials"
version = "0.1.0"
authors = ["sajith <sajith@digitalxlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
